### ISSUE TITLE
No sound on DSI

### ISSUE THREAD

**Issue by jutochoppa** [cotodevel/snemulds#1]
Do you have any idea why there is no sound on any games? they work fine otherwise. I'm using TWL method

**Comment by cotodevel** [comment]
Make sure you follow README.MD steps to boot SnemulDS (NTR or TWL mode).

**Comment by jutochoppa** [comment]
I did. weird.

**Comment by cotodevel** [comment]
Make sure you boot ToolchainGenericDS-multiboot through Unlaunch, then SnemulDS TWL.

Download the latest version indicated on the README.MD
