### ISSUE TITLE
Feature Request: SA-1 chip emulation for DSi (TWL)

### ISSUE THREAD

**Issue by radicalten** [cotodevel/snemulds#2]
Hello,

Thank you for your continued work on this project!

Based on your successful port of Street Fighter Alpha 2 and the DSP chips for DSi (TWL), would it be possible to also port the SA-1 chip, specifically to run Kirby’s Dreamland 3, Kirby Superstar, or Super Mario RPG on the DSi (TWL)?

The SA-1 chip runs at 10.74Mhz and is based on the same 65c816 processor as the main cpu. Applying the 1/10th cycle rule, theoretically the DSi’s 133Mhz should just be enough to work. 

p.s.
I also mentioned (https://github.com/Hydr8gon/sm64/issues/43) that the paging system used in SnemulDS (or a variation of it) could be applied to the Super Mario 64 DSi Port by Hydr8gon to load larger Rom sizes (>16MB) by paging to the DSi SD card. Do you think this is a reasonable idea? Sorry if this is the wrong place to ask these questions.

**Comment by cotodevel** [comment]
won't work. Both the SuperFX and SA-1 require to be rewritten entirely as HLE (then maybe later ported to assembly) for even work on SnemulDS. Given the [Ricoh 5A22](https://en.wikipedia.org/wiki/Ricoh_5A22) takes about 95% of ARM9 time @ 3.58Mhz.

Context:
https://gbatemp.net/threads/snemulds-rebirth-the-project-and-update-it-for-the-last-dkp.328636/page-33#post-10323553
