### ISSUE TITLE
Bishoujo Senshi Sailormoon bluescreen

### ISSUE THREAD

**Issue by BrianLima** [cotodevel/SnemulDS#7]
Trying to play the fan translation of the SNES RPG, downloaded the ROM from EmuParadise, won't ever load and just crashes to a blue screen
![img_20180421_002648](https://user-images.githubusercontent.com/1337383/39079954-25280060-44fb-11e8-86c1-e3a6ba0e0b8a.jpg)

**Comment by cotodevel** [comment]
1) Romhacks will mostly break, since the emulator core is missing some specific features rom hacks tend to use. 

2) Currently the cpu core barely works (some missing opcodes), that is mostly the segfault reason.


So yeah your rom needs these parts and aren't implemented for now.
