### ISSUE TITLE
Moose Chase & 3D Rotating Tower from Mickey Mania Unplayable.

### ISSUE THREAD

**Issue by ghost** [cotodevel/SnemulDS#8]
Due to the Blackscreen Preventing me from See where I'm going.

**Comment by cotodevel** [comment]
haven't delved into background modes. IIRC SnemulDS supports a few background modes fully. So yeah. Other than that, try enabling/disabling layers in settings. Fixing snemulds cpu core is much more important than background modes for now.

**Comment by pyrfil** [comment]
I tried Enable/Disable Layers on & it didn't Help.

**Comment by pyrfil** [comment]
Ink
